title = "Prospector"
gitSourceBranch = "main"

classOrder = ["Prospector"]

[home]
enabled = false
includeReadme = true

[docusaurus.themeConfig.colorMode]
respectPrefersColorScheme = true
defaultMode = "dark"