[package]
name = "egomoose/prospector"
description = "https://github.com/EgoMoose/prospector"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["test", "assets"]

[dependencies]
Promise = "evaera/promise@4.0.0"